- name: Install firefox
  become: yes
  apt:
    name:
      - firefox

- name: Clone theme
  git:
    repo: https://github.com/Lixxia/FlyingFox
    dest: '{{user_home}}/repos/FlyingFox'

- name: Find profile
  shell: 'grep Default= ~/.mozilla/firefox/profiles.ini | grep -v "^Default=1$" | sed s/^Default=//'
  register: profile_result

- debug: msg="{{profile_result.stdout}}"

- name: Link theme files
  file:
    src: '{{user_home}}/repos/FlyingFox/{{item}}'
    dest: '{{user_home}}/.mozilla/firefox/{{profile_result.stdout}}/{{item}}'
    state: link
  with_items:
    - 'chrome'
    - 'user.js'

- name: Create .config
  file:
    dest: '{{user_home}}/.config/firefox'
    state: directory

- name: Symlink startpage configs
  file:
    src: '{{dotfiles_path}}/roles/firefox/files/{{item}}'
    dest: '{{user_home}}/.config/firefox/{{item}}'
    state: link
  with_items:
    - 'style.css'
    - 'newtab.html'

- name: Symlink mozilla.cfg
  become: yes
  file:
    src: '{{dotfiles_path}}/roles/firefox/files/{{item}}'
    dest: '/usr/lib/firefox/{{item}}'
    state: link
  with_items:
    - 'mozilla.cfg'

- name: Symlink local-settings.js
  become: yes
  file:
    src: '{{dotfiles_path}}/roles/firefox/files/{{item}}'
    dest: '/usr/lib/firefox/defaults/pref/{{item}}'
    state: link
  with_items:
    - 'local-settings.js'
