- name: Install firefox
  become: yes
  apt:
    name:
      - firefox

- name: Find profile
  shell: 'grep Default= ~/.mozilla/firefox/profiles.ini | grep -v "^Default=1$" | sed s/^Default=//'
  register: profile_result

- debug: msg="{{profile_result.stdout}}"

- name: Link theme files
  file:
    src: '{{dotfiles_path}}/roles/firefox/{{item}}'
    dest: '{{user_home}}/.mozilla/firefox/{{profile_result.stdout}}/{{item}}'
    state: link
  with_items:
    - 'chrome'
    - 'user.js'
