#!/bin/bash

# Adapted from https://github.com/ntcarlson/dotfiles/blob/gamma/i3/scripts/polybar_wrapper

WINDOW_ID_TRAY=/tmp/window_id_tray

create_bar() {
    polybar $1 &
    local bar_id=$!
    echo "Polybar PID: $bar_id"
    local win_id=$(xdotool search --sync --pid $bar_id)
    echo $win_id > $2
    xdotool windowunmap $win_id
}

launch() {
    killall -q polybar
    while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
    for m in $(polybar --list-monitors | cut -d":" -f1); do
      MONITOR=$m polybar --reload main &
      bar_id=$!
    done
    echo "$bar_id"
    rm -f /tmp/polybar_mqueue_full
    ln -s /tmp/polybar_mqueue.$bar_id /tmp/polybar_mqueue_full
    create_bar tray $WINDOW_ID_TRAY &
    sleep 1
    xdotool windowunmap $(cat $WINDOW_ID_TRAY | awk '{print $2}') # auto hide tray on startup
}

rofi_open() {
    rofi -show drun -location 1 -show-icons -yoffset 28 -xoffset 3
}

search_open() {
    rofi -show window -location 1 -width 28 -yoffset 28 -xoffset 3
}

tray_open() {
    local bar_id=$(cat $WINDOW_ID_TRAY | awk '{print $2}')
         if xprop -id $bar_id | grep "Normal"; then
              xdotool windowunmap $bar_id
         elif xprop -id $bar_id | grep "Withdrawn"; then
              xdotool windowmap $bar_id
         fi
}

power_open() {
    local theme="~/.config/rofi/powermenu.rasi"
    
    local power_off=""
    local reboot="ﰇ"
    local lock=""
    local suspend="鈴"
    local log_out=""
    local options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"

    local launch="$(echo -e "$options" | rofi -theme $theme -dmenu -selected-row 2)"

    case $launch in
        $power_off)
    	    systemctl poweroff
            ;;
        $reboot)
            systemctl reboot
            ;;
        $lock)
            $HOME/.scripts/locker
            ;;
        $suspend)
            systemctl suspend
            ;;
        $log_out)
            i3-msg exit
            ;;
    esac
}

case "$1" in
    rofi)
        rofi_open
        ;;
    search)
        search_open
        ;;
    tray)
        tray_open
        ;;
    power)
        power_open
        ;;
    launch)
        launch
        ;;
esac
