- name: Install spotify
  become: yes
  command: snap install spotify

- name: Update folder ownership
  become: yes
  file:
    path: /usr/share/spotify
    state: directory
    mode: a+wr

- name: Update Apps ownership
  become: yes
  file:
    path: /usr/share/spotify/Apps
    state: directory
    recurse: yes
    mode: a+wr

- name: Get spicetify-cli
  get_url: 
    url: https://github.com/khanhas/spicetify-cli/releases/download/v2.8.4/spicetify-2.8.4-linux-amd64.tar.gz
    dest: /tmp/spicetify-2.8.4-linux-amd64.tar.gz

- name: Create spicetify-cli dir
  become: yes
  file:
    dest: /usr/local/src/spicetify-cli
    owner: '{{user}}'
    group: '{{user}}'
    mode: '0775'
    state: directory

- name: Unpack spicetify-cli
  unarchive:
    src: /tmp/spicetify-2.8.4-linux-amd64.tar.gz
    dest: /usr/local/src/spicetify-cli

- name: Setup link
  become: yes
  file:
    src: /usr/local/src/spicetify-cli/spicetify
    dest: /usr/local/bin/spicetify
    state: link

- name: Get spicetify-themes
  git:
    repo: https://github.com/morpheusthewhite/spicetify-themes.git
    dest: '{{user_home}}/repos/spicetify-themes'

- name: Make dirs
  file:
    dest: '{{user_home}}/.config/{{item}}'
    state: directory
  with_items:
    - 'spicetify'
    - 'spicetify/Themes'
    - 'spicetify/Extensions'

- name: Overwrite color.ini
  copy:
    src: '{{dotfiles_path}}/roles/spotify/files/color.ini'
    dest: '{{user_home}}/repos/spicetify-themes/Ziro/color.ini'

- name: Link theme
  file:
    src: '{{user_home}}/repos/spicetify-themes/Ziro'
    dest: '{{user_home}}/.config/spicetify/Themes/Ziro'
    state: link

- name: Update user.css
  blockinfile:
    path: '{{user_home}}/.config/spicetify/Themes/Ziro/user.css'
    insertafter: '^\* \{'
    block: "  font-family: 'Iosevka' !important;"
    marker: "/* {mark} ANSIBLE MANAGED */"

- name: Setup theme
  command: '{{item}}'
  with_items:
    - 'spicetify config current_theme Ziro color_scheme dark'
    - 'spicetify config inject_css 1 replace_colors 1 overwrite_assets 1'

- name: Check backup
  find:
    path: '{{user_home}}/.config/spicetify/Backup'
  register: spicetify_backup

- name: Backup and apply
  command: 'spicetify backup apply'
  when: spicetify_backup.matched == 0 

- name: Apply
  command: 'spicetify apply'
  when: spicetify_backup.matched > 0
