#!/usr/bin/env bash

# Taken from https://github.com/thwischm/rice/blob/3_2018/qadbar/widgets/notifications.sh

nextmessage=""

killall dunst 2> /dev/null
stdbuf -o0 dunst -geometry "0x0-0+0" -transparency 100 -print | sed -E -u \
    -e '/^\{|^\}|^\t/! d' \
    -e '/^\t\{|^\t\}|^\t{2,}|^\tactions/ d' \
    -e 's/'\''(.*)'\''$/\1/' \
    -e 's/^\t([^:]*): (.*)$/\t"\1": "\2"/' \
    -e '/^\{|^\}|^\t"script"/! s/$/,/' \
| {
    while read -r line; do
        nextmessage="$nextmessage $line"
        if [[ $line == "}" ]]; then
            echo "$nextmessage"
            nextmessage=""
        fi
    done
}
