#!/usr/bin/env python3

import sys, json, time
from datetime import datetime, timedelta
from threading import Thread

fname = '/tmp/.dunst-notification'

icons = {
    'Slack' : '',
    'Spotify' : '',
    'discord' : '',
    'geary' : '',
    'Google Chrome' : '',
    'notify-send' : ''
}

colors = {
    'LOW' : '%{F#555}',
    'NORMAL' : '%{F-}',
    'CRITICAL' : '%{F#f00}'
}

class worker(Thread):
    def __init__(self, expiry=None):
        self.expiry = expiry
        Thread.__init__(self)

    def run(self):
        while True:
            if self.expiry:
                now = datetime.utcnow()
                if self.expiry < now:
                    with open(fname, 'r+') as f:
                        last = f.readlines()[-1]
                        if last != '\n':
                            f.write('\n')
            time.sleep(5)
            
def timeout_conv(t):
    now = datetime.utcnow()
    delta = timedelta(milliseconds=t)
    expiry = now + delta
    return expiry
    
w = worker()
w.start()
while True:
  line = sys.stdin.readline()
  j = json.loads(line)

  with open(fname, 'a') as file:
    try:
        data = (icons[j["appname"]] + " " + j["summary"] + "  " + j["body"])
    except:
        data = (icons["notify-send"] + " " + j["summary"] + "  " + j["body"])
    #print(colors[j["urgency"]] + data[:40] + (data[40:] and '...') + "%{F-}\n")
    file.write(colors[j["urgency"]] + data[:40] + (data[40:] and '...') + "%{F-}\n")
    w.expiry = timeout_conv(int(j['timeout']))

