#!/usr/bin/env python3

import sys, json, time

fname = '/tmp/.dunst-notification'

icons = {
    'Slack' : '',
    'Spotify' : '',
    'discord' : '',
    'geary' : '',
    'Google Chrome' : '',
    'notify-send' : ''
}

colors = {
    'LOW' : '%{F#555}',
    'NORMAL' : '%{F-}',
    'CRITICAL' : '%{F#f00}'
}

while True:
  line = sys.stdin.readline()
  j = json.loads(line)

  with open(fname, 'a') as file:
    try:
        data = (icons[j["appname"]] + " " + j["summary"] + "  " + j["body"])
    except:
        data = (icons["notify-send"] + " " + j["summary"] + "  " + j["body"])
    #print(colors[j["urgency"]] + data[:40] + (data[40:] and '...') + "%{F-}\n")
    file.write(colors[j["urgency"]] + data[:40] + (data[40:] and '...') + "%{F-}\n")

