- name: Install misc packages
  become: yes
  apt:
    name: 
      - curl
      - xdotool
      - wmctrl
      - git
      - vim
      - gcc
      - make
      - automake
      - autoconf
      - python3-pip
      - ruby
      - pavucontrol
      - xbindkeys
      - xautomation

- name: Install Go
  get_url:
    url: https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
    dest: /tmp/go1.15.2.linux-amd64.tar.gz

- name: Unarchive Go
  become: yes
  unarchive:
    src: /tmp/go1.15.2.linux-amd64.tar.gz
    dest: /usr/local

- name: Install Slack
  become: yes
  command: snap install slack --classic

- name: Install discord
  become: yes
  command: snap install discord

- name: Link xbindkeys config
  file:
    path: '{{dotfiles_path}}/roles/misc/files/.xbindkeysrc'
    dest: '{{user_home}}/.xbindkeysrc'
    state: link

# install npm

# install terraform (apt repo add + install"")
# terraform-docs
# install pre-commit (pip)
