- name: "Add GnuPG key: Steam."
  apt_key:
    url: https://repo.steampowered.com/steam/archive/precise/steam.gpg
    state: present

- name: "Add Repo: Steam"
  apt_repository:
    repo: deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam
    state: present
    filename: 'steam'

- name: "Add Repo: Steam src"
  apt_repository:
    repo: deb-src [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam
    state: present
    filename: 'steam'

- name: "Install steam"
  apt: 
    name: steam
    state: present 
    update_cache: yes
