- name: Install nvim
  become: yes
  command: snap install nvim --classic
  when: ansible_facts['os_family'] == "Debian"

- name: Install nvim
  command: brew install nvim
  when: ansible_facts['os_family'] == "Darwin"

- name: Setup config dir
  file:
    path: '{{user_home}}/.config/nvim'
    state: directory

- name: Setup share dir
  file:
    path: '{{user_home}}/.local/share/nvim/site/autoload'
    state: directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: '{{user_home}}/.local/share/nvim/site/autoload/plug.vim'

- name: Symlink configs
  file:
    src: '{{dotfiles_path}}/roles/nvim/files'
    dest: '{{user_home}}/.config/nvim'
    state: link

- name: Install plugins
  command: nvim +PlugInstall +qall
